language: go

go:
  - 1.1
  - 1.2
  - 1.3
  - 1.4
  - tip

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install libcv-dev libhighgui-dev libopencv-dev

notifications:
  email:
    on_success: change
    on_failure: always
