language: go

go:
  - 1.1
  - 1.2
  - 1.3
  - 1.4
  - tip

before_install:
  - sudo add-apt-repository -y ppa:kubuntu-ppa/backports 
  - sudo apt-get update -qq
  - sudo apt-get install libcv-dev libopencv-dev libopencv-contrib-dev libhighgui-dev libopencv-photo-dev libopencv-imgproc-dev libopencv-stitching-dev libopencv-superres-dev libopencv-ts-dev libopencv-videostab-dev 

notifications:
  email:
    on_success: change
    on_failure: always
